### PR TITLE
update project

### PR DESCRIPTION
**Pull request by corinnekrych**

### CODE REVIEW

**Comment by corinnekrych** [comment]
@danbev as discussed here is an update for the project file.

**Comment by danbev** [comment]
@corinnekrych Thanks! I got conflicts which are hard to resolve. Might be better if I simply replace the project file with yours. Will take another look at this in the morning. I got the tests working on your fork so hopefully we'll have this working tomorrow. Catch up with you tomorrow.

**Comment by corinnekrych** [comment]
Whatever works for you
Let's catch up tomorrow i'd love to hear the end of the story :)

**Comment by danbev** [comment]
@corinnekrych I've commited your fix in 56efa8be944c7943d23c4ea0e0313e7203d9c87a. Was just easier than having to go through the project file and handling the conflicts.

**Pull request closed without merging**
